Feature/bliss 634/update sample app
usabilla/usabilla-u4a-xamarin pull request #42
Opened 2020-11-17 15:52 UTC by demirsoya

- Update sample app new with the new look provided by designers.

2020-12-21 16:09 UTC, hiteshjain29 commented
> ![Screenshot 2020-11-18 at 14 26 11](https://user-images.githubusercontent.com/64772498/99536539-d0408300-29aa-11eb-862e-16f580b87603.png)
> ![Screenshot 2020-11-18 at 14 25 42](https://user-images.githubusercontent.com/64772498/99536547-d20a4680-29aa-11eb-9e3a-c84b14a1e065.png)
> ![Screenshot 2020-11-18 at 14 27 54](https://user-images.githubusercontent.com/64772498/99536557-d5053700-29aa-11eb-8ba4-94c34b3fdc27.png)
> 
> * Update sample app new with the new look provided by designers.

2020-12-21 16:18 UTC, hiteshjain29 requested changes

2020-12-21 16:18 UTC, hiteshjain29 commented on UsabillaBindings/Xamarin.Usabilla.Sample/MainPage.xaml
> +            RelativeLayout.HeightConstraint=
![Screenshot 2020-12-21 at 17 16 13](https://user-images.githubusercontent.com/42991157/102797649-47a17200-43b0-11eb-99d5-22088cff98f3.png)

@demirsoya, As per this wireframe, logo should be in the bottom and text will be on the top.

2021-01-07 13:56 UTC, hiteshjain29 commented on UsabillaBindings/Xamarin.Usabilla.Sample/MainPage.xaml
> +            RelativeLayout.HeightConstraint=
@demirsoya i still see little bit of differences.

2021-01-07 13:58 UTC, demirsoya commented on UsabillaBindings/Xamarin.Usabilla.Sample/MainPage.xaml
> +            RelativeLayout.HeightConstraint=
what exactly you wanted to be changed?

2021-01-19 14:26 UTC, hiteshjain29 approved these changes

2021-01-19 14:55 UTC, merged