Add preload feedback forms support
usabilla/usabilla-u4a-xamarin pull request #44
Opened 2020-12-21 15:50 UTC by demirsoya

Add preload feedback forms support and update packages to latest.

2020-12-21 16:05 UTC, hiteshjain29 requested changes

2020-12-21 16:05 UTC, hiteshjain29 commented on UsabillaBindings/Xamarin.Usabilla.Android/Xamarin.Usabilla.Android/UsabillaXamarin.cs
> +            Log.Debug("UBInfo", "Preloading feedback forms: " + String.Join(',', formIds));
If there is a debug flag already available in interface, than this might be extra debugs which can be removed, once tested.

2020-12-21 16:05 UTC, hiteshjain29 commented on UsabillaBindings/Xamarin.Usabilla.Sample/mono_crash.11a6748113.0.json
> +}
Is this file required?

2020-12-22 12:21 UTC, demirsoya commented on UsabillaBindings/Xamarin.Usabilla.Android/Xamarin.Usabilla.Android/UsabillaXamarin.cs
> +            Log.Debug("UBInfo", "Preloading feedback forms: " + String.Join(',', formIds));
Sure but; we also have this logging in the method which were already there. You want me to remove logging from all?

2020-12-22 12:33 UTC, hiteshjain29 commented on UsabillaBindings/Xamarin.Usabilla.Android/Xamarin.Usabilla.Android/UsabillaXamarin.cs
> +            Log.Debug("UBInfo", "Preloading feedback forms: " + String.Join(',', formIds));
If it's not needed, for any specific purpose than yes.

2021-01-15 08:20 UTC, closed without merging